apiVersion: v1
data:
    adminPassword: ENC[AES256_GCM,data:zmiJxxijg2Cu1JzMwLk2zn8bNPyQcUSHV7rrsQ==,iv:1MvcDAhjEjm7KT63IXCJ9YzzoX+26AiFQb648hzfmuw=,tag:FM3BOk4KT5toa8xD9f/hDA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-secret
sops:
    age:
        - recipient: age1m7uqtvawfv37ceccgccq4d07wqxuv5jqrswdz9u5tqlc0erm8gtqr6pgq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ2kra1MrdjBnSnV4Qkds
            OXc4MmFaYXlkcGJaSmhmS0FYQ2ZreUJCc21NClRqUS9QY1R4QXZyS0VRcWFZdlVC
            azRUbnlYRUk3ZXpTd0ZNblVydVovZ0kKLS0tIFdOSUNkRTU0ZDQ1WHVNOHczZFUr
            UTM3cElsaHlRMTc0eU5YdUozWmczNDgK1H/GYakKD1FAMk58uBOKwWQztmld0iXD
            5Le+oxs3Xqi+oqZMCC2sGl9NkOhqd3J0afwcyQy+3d4d/32kotB6+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:28:48Z"
    mac: ENC[AES256_GCM,data:8ExjsYhl36auhV4uk2wvL6nJATb+y31veVhacmvFsMHrKNZSnl3gRvNs7wPdHbuXm26585owQ0cJVcEBZkxKp/OzJ/906BvVpF02Bk7vioJJ5BLE26rhVAGZkknEIG4ZGxDtg7m1Znhjh3raDPbry1+MpTfEwfvSKGqt8Qz2p3I=,iv:2EMs5jJx3B7Hw5LPBGysL6Q98FNoQS/+AjmlAE1ccvs=,tag:343jGDHGZtkRTDto49K2Fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
