apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - abs-audiobooks.yaml
  - abs-config.yaml
  - abs-metadata.yaml
  - abs-podcasts.yaml
  - service.yaml
  - config.yaml
