apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:tvQvVaVIYO98Fa5iGHc57L3Qu03zgpm2Go+UjePWiRp5QJzmyPpOMQVM7q91l7JUMDt7d19zu1qVRFpn8ieNWwvQK6MidHm1F0/XB4NepQF5TTkDu55RulYzE5d7kzt/x19d+O2FgBQTnDmNuEj0U7AKUHLWELKtLZ4T+pfeEc6PRZUV7YCTABOqYk3lr5FF8ubq2Ab6A2+3YyJvrqUhCZfFtkIIwlXm4Ra0NifyOgt199Jt91USUClbKxwWmkdbyTff23Y6LWlDcrJw73LtJqhzSi54pLnraG6Inp6vPdkBv+tMMieNH5jT43w=,iv:E660F/F3Ar8QDDC0DRq2FqLOtCmNCUciIdYSgjD4M+s=,tag:yvRTsSGlzM6VuszJFELGjw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1m7uqtvawfv37ceccgccq4d07wqxuv5jqrswdz9u5tqlc0erm8gtqr6pgq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENzN3MjYvWE1mUkpnampL
            aHpWZzNqZ3FibjZ2cTJQQStJY3I5Z0RSUVVBCktRQXdmdGpwc2FvME9WS0hDQXh3
            S3FSdC8yWGd2akxpM3YrTW1KTHhtM0kKLS0tIGlKM1QyTGxwaGFtSEkzb21aOWJI
            cWs3Vys5VHFJbmdMMmUzeDZvRnlvc3MKrN8MF5yWvgluaMJoM2aqHmbY4fv4A7kU
            nT6N6Hvb5cb/N+CpQNEx9s5zz/l426kKib0EOGJj+7MxEBoNww1XUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T21:37:11Z"
    mac: ENC[AES256_GCM,data:PfTQrqr/N+tafXXU/zgHxzPZyIWJOkfbUGiSRRzj+Bu+OmZLArSqH2eNx3T6/G833uMaouqeWlXx9FTn5OWMlnF90QZ7/VZZffhCAF4+16b3sHQe84/Ac+rrOnrnjoS0IDNU2y0JySZK7n2ms1ZrhuvoJTsj/QKq1rFgA14toFI=,iv:347Mw+LNX7bdy8Vl0/0DtyscW2BHmgY0ZYQFakUlDNM=,tag:LOGnXfpNmqGyHAFI/gwf+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
