apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:7jSIocTHypyKDuP+cRxdXg==,iv:Sx+e4d2zhlGpQIbk1YkRMOIc2YPRE1a/TskM8/GHKgQ=,tag:20lVV4z89tAhhKl/hBcVPw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:CgMLHJiYPJPhonjaNTegTp4lhYHt2MQxI2Fmdw==,iv:+tJC/sxPiAef61C+kmMfSUJbkoXmWi1P38cdJIzayfI=,tag:hVGK2oLO48FCZv7n9GEo0w==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1m7uqtvawfv37ceccgccq4d07wqxuv5jqrswdz9u5tqlc0erm8gtqr6pgq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eWRkdWZMUC9rdlk1S0hC
            M1NPc3NmNDYzajRCMmtGVythWi8xc0wxcmpnCkk1a1BCYzNSUmNXK2lpWWJXaUFs
            NWFqYSs5aUhhajJPa1c5TGtQeTdYV2cKLS0tIFpXRzJLWTBJNTZvSjB5MUo2cWZv
            dHloeUJ1UmZhTTg1SmdFVHUzWXlrbUUKYhQKbJcmvjFDpIMsEXvo1rpy/zF+FoyA
            kKLlpwZ/IlblESCJnTel9kfiI9MvAGC0pPz29DDgAgbC1LemNI1VcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T22:20:57Z"
    mac: ENC[AES256_GCM,data:Mm+fZtv2UHxc8DD7a9Mc7xSzn5moGiuTxCCMi2kCxv6qct/U3KeCVLNc0j48olDqwgJ06IhmMEzY5Z9mpIvAi3q4Z7GSWHiGVPzXhbIFqEbe85zb6x6SwLh2ottLfe8CPDKMBkXNsrpAUjq0R4sUKsR5HxjsYE3+fl6iPMOih8A=,iv:etUjC0WcynQz1pdCTk/a5IjIE7OYugAYiQ/so6QrhgM=,tag:OswUlRb5X15umx/3FTL4Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
