apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec: # --- Start of the "What to do" section
  interval: 1m0s
  path: ./monitoring/controllers/staging
  prune: true
